---
title: "Introduction to Data Analysis with R"
author: "Federico Roscioli"
date: "`r format(Sys.time(), '%d %B, %Y')`"
site: "bookdown::bookdown_site"
documentclass: svmono
output:
  bookdown::pdf_book:
    keep_tex: yes
    toc: true
    extra_dependencies: ["float"]
    toc_depth: 3
    number_sections: true
    pandoc_args: --top-level-division=chapter
  bookdown::gitbook:
    config:
      toc:
        collapse: section
        toc_depth: 1
        scroll_highlight: yes
        before: null
    number_sections: TRUE
  rmdformats::downcute:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
urlcolor: blue
editor_options: 
  markdown: 
    wrap: 72
bibliography: references.bib
biblio-style: apalike
link-citations: yes
header-includes:
- \usepackage{caption}
- \usepackage{ragged2e}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead[L]{Introduction to Data Analysis with R}
- \fancyfoot[C]{www.federicoroscioli.com}
- \fancyfoot[LE,RO]{\thepage}
- \fancyfoot[LO,RE]{v. 5.0}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=6, fig.height=3, fig.pos = 'H', out.extra = "")
```


# Preface {.unnumbered}

<!-- Add Spatial inference -->

The real goal of this manual is not to teach the R language per se, but
to allow the students to manage the basic concepts in order to be able
to explore and analyze data using R. After this course the student will
be capable of clearly understand the R code that someone else wrote and
customize her own code according to the need. This means having the
possibility to explore different and more complex solutions for the
student's problems by exploring new packages and paving the way to
become a statistician!

---

I also created also an ad-hoc **R playground** accessible
[here](https://federicoroscioli.shinyapps.io/exercises/). The R
playground allows the student to exercise in order to reinforce her
knowledge of R and data analysis. Exercises are fundamental in order to
fix the knowledge acquired in class. The platform is structured in the
same way as this manual in order to have a linear learning process. I
finally want to remark that the code I provide is "my best and easiest
version of the solution", I hope you will appreciate it. In fact, with
R, it is possible to do the same thing in 1000 different ways, and by
looking at the internet you can have a confirmation of it.

---

This website is free to use, and is licensed under the GNU General Public
License 2.0. If you’d like a pdf copy of the book, you can download it [here](https://github.com/federicoroscioli/book/blob/2b55c0f10dac709bf83a6edc26c7175128c34cd3/docs/_main.pdf).

## Author {.unnumbered}
**Federico Roscioli** is a PhD Student in Economics and Finance at the University of Rome Tor Vergata. He has an international experience as a consultant for various International Organizations and Research Institutes and a background as freelance photojournalist. His research interests include: development issues, environmental sustainability, poverty, social protection, food security and nutrition. 
[www.federicoroscioli.com](https://www.federicoroscioli.com/)

## Acknowledgements {.unnumbered}
This book was written following the teachings of Matteo Mazziotta (ISTAT).

\newpage
